const screenShots = [
    '01_Login.png',
    '02_Home.png',
    '04_Files.png',
    '05_Files-file-context-dropdown.png',
    '06_Files-delete-click.png',
    '07_Shorts.png',
    '08_Shorts-create.png',
    '09_Shorts-delete-click.png',
    '10_Shorts-delete-deleted.png',
    '11_Stats.png',
    '12_Settings-User.png',
    '13_Settings-User-save-settings.png',
    '14_Settings-delete-click.png',
    '15_Settings-delete-deleted.png',
    '16_Public-disabled-redirect.png',
    '17_Settings-Site-save-settings.png',
    '18_Settings-Site-flush-cache.png',
    '20_Public-enabled.png',
    '21_Preview-gps2.jpg.png',
    '23_Preview-README.md.png',
    '27_Preview-an225.jpg.png',
    '29_Site Settings with Global Quota Near Full.png',
    '30_Upload Failed by Global Quota.png',
    '31_File-password.png',
    '32_Logout.png',
]
