timezone: America/Los_Angeles
encoding: utf-8

author: Shane/Ralph
site_name: Django Files
site_url: https://django-files.github.io/
github_url: https://github.com/django-files/django-files

chrome_url: https://chromewebstore.google.com/detail/django-files/abpbiefojfkekhkjnpakpekkpeibnjej
firefox_url: https://addons.mozilla.org/en-US/firefox/addon/django-files/
chrome_id: abpbiefojfkekhkjnpakpekkpeibnjej
firefox_id: django-files
github_name: django-files/web-extension
