const screenShots = [
    '/screenshots/01_Login.png',
    '/screenshots/02_Home.png',
    '/screenshots/05_Files-file-context-dropdown.png',
    '/screenshots/06_Files-delete-click.png',
    '/screenshots/08_Shorts-create.png',
    '/screenshots/09_Shorts-delete-click.png',
    '/screenshots/11_Stats.png',
    '/screenshots/13_Settings-User-save-settings.png',
    '/screenshots/14_Settings-delete-click.png',
    '/screenshots/15_Settings-delete-deleted.png',
    '/screenshots/18_Settings-Site-flush-cache.png',
    '/screenshots/20_Public-enabled.png',
    '/screenshots/21_Preview-gps2.jpg.png',
    '/screenshots/23_Preview-README.md.png',
    '/screenshots/27_Preview-an225.jpg.png',
    '/screenshots/29_Site Settings with Global Quota Near Full.png',
    '/screenshots/30_Upload Failed by Global Quota.png',
    '/screenshots/31_Logout.png',
    '/screenshots/33_File-password.png',
]
