timezone: America/Los_Angeles
encoding: utf-8

url: https://django-files.github.io

author: Shane/Ralph
site_name: Django Files

menu:
  - name: Home
    link: /
  - name: Docs
    link: /docs/
  - name: Screen Shots
    link: /screenshots/
  - name: iOS
    link: /ios/
  - name: Android
    link: /android/
  - name: Browser
    link: /extension/

ext_repo: web-extension
extension_github: https://github.com/django-files/web-extension

chrome_id: abpbiefojfkekhkjnpakpekkpeibnjej
chrome_url: https://chromewebstore.google.com/detail/django-files/abpbiefojfkekhkjnpakpekkpeibnjej

firefox_id: django-files
firefox_url: https://addons.mozilla.org/en-US/firefox/addon/django-files/

discord_invite: https://discord.gg/wXy6m2X8wY
discord_server: 899171661457293343

relay_url: https://relay.cssnr.com/discord/1258944618389569566

github_org: django-files
github_repo: django-files
github_org_url: https://github.com/django-files
github_full_url: https://github.com/django-files/django-files

ios_repo: ios-client
android_repo: android-client
