name: "Pages"

on:
  push:
    branches:
      - "master"
    paths:
      - "docs/**"
      - ".vitepress/**"
      - "package.json"
      - ".github/workflows/pages.yaml"
  workflow_dispatch:

env:
  CRAWLER_ID: 740ca24d-65fd-4f25-b397-16ebcec2f7fd
  CRAWLER_USER_ID: ${{ secrets.CRAWLER_USER_ID }}
  CRAWLER_API_KEY: ${{ secrets.CRAWLER_API_KEY }}

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: "Setup Node 22"
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - name: "Configure Pages"
        uses: actions/configure-pages@v5

      - name: "Install Dependencies"
        run: |
          npm ci

      - name: "Run Build"
        run: |
          npm run build

      - name: "Upload Pages Artifact"
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: "Deploy Pages"
        id: deployment
        uses: actions/deploy-pages@v4

      - name: "Send Deploy Notification"
        if: ${{ !cancelled() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  post:
    name: "Post-Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: deploy

    steps:
      - name: "Algolia Start Crawl"
        if: ${{ !cancelled() }}
        uses: cssnr/web-request-action@v1
        with:
          url: https://crawler.algolia.com/api/1/crawlers/${{ env.CRAWLER_ID }}/reindex
          username: ${{ env.CRAWLER_USER_ID }}
          password: ${{ env.CRAWLER_API_KEY }}

      - name: "Send Post-Deploy Notification"
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
